### ISSUE TITLE
updated mods

### ISSUE THREAD

**Issue by nacho1191** [cappig/steam-workshop-downloader#2]
hey, it's a bug where OI try to download an updated mod and the download is an older version?
example https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252

**Comment by cappig** [comment]
Unfortunately valve doesn't permit users to download mods for games they don't own. So this script relies on sites where users or mod creators upload mods and assets (mainly [smods.ru](https://smods.ru/)). Since this is all done by hand the mods are not guarantied to be up to date.

[smods.ru](https://smods.ru/) allows users to request updates to mods. Click the [Request updates for this game](https://goo.gl/forms/qcgqEl1XcGCumgum1) button in the left column.

**Comment by cappig** [comment]
I'll close this issue for now. Feel free to reopen if you have any more questions.
